let workPackage1 = [
  {
    workPackage: 1,
    concurrentWP: 1,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "jan 5",
    endDate: "jan 20",
    length: 15,
    cost: 110000,
    estimateAcuracy: 1,
    quote: true,
    ID: 54321,
  },
  {
    workPackage: 1,
    concurrentWP: 1,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "jan 8",
    endDate: "jan 20",
    length: 12,
    cost: 80000,
    quote: true,
    ID: 54322,
  },
  {
    workPackage: 1,
    concurrentWP: 1,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "jan 2",
    endDate: "jan 14",
    length: 12,
    cost: 130000,
    quote: false,
    ID: 54323,
  },
  {
    workPackage: 1,
    concurrentWP: 1,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "jan 6",
    endDate: "jan 14",
    length: 8,
    cost: 90000,
    quote: true,
    ID: 54324,
  },
  {
    workPackage: 1,
    concurrentWP: 1,
    vendor: "ericcson",
    uniform2: "abc",
    startDate: "jan 3",
    endDate: "jan 7",
    length: 4,
    cost: 5000,
    quote: false,
    ID: 54325,
  },
];

let workPackage2 = [
  {
    workPackage: 2,
    concurrentWP: 1,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "jan 7",
    endDate: "jan 17",
    length: 10,
    cost: 75000,
    quote: true,
    ID: 54326,
  },
  {
    workPackage: 2,
    concurrentWP: 1,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "jan 2",
    endDate: "jan 13",
    length: 11,
    cost: 110000,
    quote: true,
    ID: 54327,
  },
  {
    workPackage: 2,
    concurrentWP: 1,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "jan 5",
    endDate: "jan 13",
    length: 8,
    cost: 10000,
    quote: false,
    ID: 54328,
  },
];

let workPackage3 = [
  {
    workPackage: 3,
    concurrentWP: 1,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "jan 4",
    endDate: "jan 19",
    length: 15,
    cost: 120000,
    quote: true,
    ID: 54329,
  },
  {
    workPackage: 3,
    concurrentWP: 1,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "jan 9",
    endDate: "jan 16",
    length: 7,
    cost: 85000,
    quote: false,
    ID: 54330,
  },
  {
    workPackage: 3,
    concurrentWP: 1,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "jan 1",
    endDate: "jan 12",
    length: 11,
    cost: 120000,
    quote: true,
    ID: 54331,
  },
  {
    workPackage: 3,
    concurrentWP: 1,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "jan 4",
    endDate: "jan 12",
    length: 8,
    cost: 12000,
    quote: false,
    ID: 54332,
  },
];

let workPackage4 = [
  {
    workPackage: 4,
    concurrentWP: 1,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "jan 6",
    endDate: "jan 15",
    length: 9,
    cost: 110000,
    quote: true,
    ID: 54333,
  },
  {
    workPackage: 4,
    concurrentWP: 1,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "jan 2",
    endDate: "jan 14",
    length: 12,
    cost: 90000,
    quote: false,
    ID: 54334,
  },
  {
    workPackage: 4,
    concurrentWP: 1,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "jan 5",
    endDate: "jan 18",
    length: 13,
    cost: 100000,
    quote: true,
    ID: 54335,
  },
  {
    workPackage: 4,
    concurrentWP: 1,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "jan 3",
    endDate: "jan 16",
    length: 13,
    cost: 95000,
    quote: true,
    ID: 54336,
  },
];

let workPackage5 = [
  {
    workPackage: 5,
    concurrentWP: 2,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "feb 8",
    endDate: "feb 17",
    length: 9,
    cost: 80000,
    quote: false,
    ID: 54337,
  },
  {
    workPackage: 5,
    concurrentWP: 2,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "feb 2",
    endDate: "feb 13",
    length: 11,
    cost: 130000,
    quote: true,
    ID: 54338,
  },
  {
    workPackage: 5,
    concurrentWP: 2,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "feb 7",
    endDate: "feb 16",
    length: 9,
    cost: 110000,
    quote: false,
    ID: 54339,
  },
  {
    workPackage: 5,
    concurrentWP: 2,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "feb 4",
    endDate: "feb 19",
    length: 15,
    cost: 95000,
    quote: true,
    ID: 54340,
  },
];

let workPackage6 = [
  {
    workPackage: 6,
    concurrentWP: 2,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "feb 3",
    endDate: "feb 15",
    length: 12,
    cost: 105000,
    quote: true,
    ID: 54341,
  },
  {
    workPackage: 6,
    concurrentWP: 2,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "feb 6",
    endDate: "feb 19",
    length: 13,
    cost: 88000,
    quote: false,
    ID: 54342,
  },
  {
    workPackage: 6,
    concurrentWP: 2,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "feb 1",
    endDate: "feb 14",
    length: 13,
    cost: 120000,
    quote: true,
    ID: 54343,
  },
  {
    workPackage: 6,
    concurrentWP: 2,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "feb 5",
    endDate: "feb 18",
    length: 13,
    cost: 100000,
    quote: false,
    ID: 54344,
  },
];

let workPackage7 = [
  {
    workPackage: 7,
    concurrentWP: 3,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "mar 4",
    endDate: "mar 16",
    length: 12,
    cost: 95000,
    quote: true,
    ID: 54345,
  },
  {
    workPackage: 7,
    concurrentWP: 3,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "mar 7",
    endDate: "mar 15",
    length: 8,
    cost: 110000,
    quote: false,
    ID: 54346,
  },
  {
    workPackage: 7,
    concurrentWP: 3,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "mar 2",
    endDate: "mar 13",
    length: 11,
    cost: 80000,
    quote: true,
    ID: 54347,
  },
  {
    workPackage: 7,
    concurrentWP: 3,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "mar 6",
    endDate: "mar 18",
    length: 12,
    cost: 120000,
    quote: false,
    ID: 54348,
  },
];

let workPackage8 = [
  {
    workPackage: 8,
    concurrentWP: 3,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "mar 5",
    endDate: "mar 19",
    length: 14,
    cost: 100000,
    quote: true,
    ID: 54349,
  },
  {
    workPackage: 8,
    concurrentWP: 3,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "mar 9",
    endDate: "mar 17",
    length: 8,
    cost: 85000,
    quote: false,
    ID: 54350,
  },
  {
    workPackage: 8,
    concurrentWP: 3,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "mar 1",
    endDate: "mar 14",
    length: 13,
    cost: 110000,
    quote: true,
    ID: 54351,
  },
  {
    workPackage: 8,
    concurrentWP: 3,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "mar 4",
    endDate: "mar 16",
    length: 12,
    cost: 95000,
    quote: false,
    ID: 54352,
  },
];

let workPackage9 = [
  {
    workPackage: 9,
    concurrentWP: 3,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "mar 6",
    endDate: "mar 20",
    length: 14,
    cost: 130000,
    quote: true,
    ID: 54353,
  },
  {
    workPackage: 9,
    concurrentWP: 3,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "mar 2",
    endDate: "mar 14",
    length: 12,
    cost: 90000,
    quote: false,
    ID: 54354,
  },
  {
    workPackage: 9,
    concurrentWP: 3,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "mar 5",
    endDate: "mar 18",
    length: 13,
    cost: 100000,
    quote: true,
    ID: 54355,
  },
  {
    workPackage: 9,
    concurrentWP: 3,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "mar 3",
    endDate: "mar 16",
    length: 13,
    cost: 95000,
    quote: true,
    ID: 54356,
  },
];

let workPackage10 = [
  {
    workPackage: 10,
    concurrentWP: 4,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "apr 8",
    endDate: "apr 17",
    length: 9,
    cost: 80000,
    quote: false,
    ID: 54357,
  },
  {
    workPackage: 10,
    concurrentWP: 4,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "apr 2",
    endDate: "apr 13",
    length: 11,
    cost: 130000,
    quote: true,
    ID: 54358,
  },
  {
    workPackage: 10,
    concurrentWP: 4,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "apr 7",
    endDate: "apr 16",
    length: 9,
    cost: 110000,
    quote: false,
    ID: 54359,
  },
  {
    workPackage: 10,
    concurrentWP: 4,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "apr 4",
    endDate: "apr 19",
    length: 15,
    cost: 95000,
    quote: true,
    ID: 54360,
  },
];

let workPackage11 = [
  {
    workPackage: 11,
    concurrentWP: 4,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "apr 3",
    endDate: "apr 15",
    length: 12,
    cost: 105000,
    quote: true,
    ID: 54361,
  },
  {
    workPackage: 11,
    concurrentWP: 4,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "apr 6",
    endDate: "apr 19",
    length: 13,
    cost: 88000,
    quote: false,
    ID: 54362,
  },
  {
    workPackage: 11,
    concurrentWP: 4,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "apr 2",
    endDate: "apr 15",
    length: 13,
    cost: 120000,
    quote: true,
    ID: 54363,
  },
  {
    workPackage: 11,
    concurrentWP: 4,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "apr 5",
    endDate: "apr 18",
    length: 13,
    cost: 100000,
    quote: false,
    ID: 54364,
  },
];

let workPackage12 = [
  {
    workPackage: 12,
    concurrentWP: 4,
    vendor: "amazon",
    uniform2: "abc",
    startDate: "apr 4",
    endDate: "apr 16",
    length: 12,
    cost: 95000,
    quote: true,
    ID: 54365,
  },
  {
    workPackage: 12,
    concurrentWP: 4,
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "apr 7",
    endDate: "apr 15",
    length: 8,
    cost: 110000,
    quote: false,
    ID: 54366,
  },
  {
    workPackage: 1,
    concurrentWP: 4,
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "apr 2",
    endDate: "apr 13",
    length: 11,
    cost: 80000,
    quote: true,
    ID: 54367,
  },
  {
    workPackage: 12,
    concurrentWP: 4,
    vendor: "dennys",
    uniform2: "abc",
    startDate: "apr 6",
    endDate: "apr 18",
    length: 12,
    cost: 120000,
    quote: false,
    ID: 54368,
  },
];

let concurrentWP1 = [workPackage1, workPackage2, workPackage3, workPackage4];
let concurrentWP2 = [workPackage5, workPackage6];
let concurrentWP3 = [workPackage7, workPackage8, workPackage9];
let concurrentWP4 = [workPackage10, workPackage11, workPackage12];

export { concurrentWP1, concurrentWP2, concurrentWP3 };

// function checkDurationMatchesDates(concurrentWP) {
//   concurrentWP.forEach((workPackages, index) => {
//     workPackages.forEach((wp) => {
//       const startDate = new Date(wp.startDate);
//       const endDate = new Date(wp.endDate);
//       const calculatedDuration = (endDate - startDate) / (1000 * 60 * 60 * 24); // Duration in days

//       if (calculatedDuration !== wp.length) {
//         console.log(
//           `Mismatch found in concurrentWP[${index}] - workPackage ${wp.workPackage}, ID ${wp.ID}`
//         );
//         console.log(
//           `Expected duration: ${wp.length} days, Calculated duration: ${calculatedDuration} days`
//         );
//       }
//     });
//   });
// }

// checkDurationMatchesDates(concurrentWP1);
// checkDurationMatchesDates(concurrentWP2);
// checkDurationMatchesDates(concurrentWP3);
// checkDurationMatchesDates(concurrentWP4);
