let job1 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "jan 5",
    endDate: "jan 20",
    length: 12,
    cost: 110000,
    quote: true,
    bidID: 54321,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "jan 8",
    endDate: "jan 20",
    length: 10,
    cost: 80000,
    quote: true,
    bidID: 54322,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "jan 2",
    endDate: "jan 14",
    length: 14,
    cost: 130000,
    quote: false,
    bidID: 54323,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "jan 6",
    endDate: "jan 14",
    length: 8,
    cost: 90000,
    quote: true,
    bidID: 54324,
  },
];

let job2 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "jan 3",
    endDate: "jan 18",
    length: 16,
    cost: 95000,
    quote: false,
    bidID: 54325,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "jan 7",
    endDate: "jan 17",
    length: 13,
    cost: 75000,
    quote: true,
    bidID: 54326,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "jan 2",
    endDate: "jan 13",
    length: 11,
    cost: 110000,
    quote: true,
    bidID: 54327,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "jan 5",
    endDate: "jan 13",
    length: 10,
    cost: 100000,
    quote: false,
    bidID: 54328,
  },
];

let job3 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "jan 4",
    endDate: "jan 19",
    length: 14,
    cost: 120000,
    quote: true,
    bidID: 54329,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "jan 9",
    endDate: "jan 16",
    length: 12,
    cost: 85000,
    quote: false,
    bidID: 54330,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "jan 1",
    endDate: "jan 12",
    length: 13,
    cost: 120000,
    quote: true,
    bidID: 12345,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "jan 4",
    endDate: "jan 12",
    length: 9,
    cost: 120000,
    quote: false,
    bidID: 12345,
  },
];

let job4 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "feb 6",
    endDate: "feb 15",
    length: 15,
    cost: 110000,
    quote: true,
    bidID: 54331,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "feb 2",
    endDate: "feb 14",
    length: 12,
    cost: 90000,
    quote: false,
    bidID: 54332,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "feb 5",
    endDate: "feb 18",
    length: 14,
    cost: 100000,
    quote: true,
    bidID: 54333,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "feb 3",
    endDate: "feb 16",
    length: 11,
    cost: 95000,
    quote: true,
    bidID: 54334,
  },
];

let job5 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "feb 8",
    endDate: "feb 17",
    length: 13,
    cost: 80000,
    quote: false,
    bidID: 54335,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "feb 2",
    endDate: "feb 13",
    length: 10,
    cost: 130000,
    quote: true,
    bidID: 54336,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "feb 7",
    endDate: "feb 16",
    length: 12,
    cost: 110000,
    quote: false,
    bidID: 54337,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "feb 4",
    endDate: "feb 19",
    length: 16,
    cost: 95000,
    quote: true,
    bidID: 54338,
  },
];

let job6 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "feb 3",
    endDate: "feb 15",
    length: 11,
    cost: 105000,
    quote: true,
    bidID: 54339,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "feb 6",
    endDate: "feb 19",
    length: 14,
    cost: 88000,
    quote: false,
    bidID: 54340,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "feb 1",
    endDate: "feb 14",
    length: 9,
    cost: 120000,
    quote: true,
    bidID: 54341,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "feb 5",
    endDate: "feb 18",
    length: 13,
    cost: 100000,
    quote: false,
    bidID: 54342,
  },
];

let job7 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "mar 4",
    endDate: "mar 16",
    length: 12,
    cost: 95000,
    quote: true,
    bidID: 54343,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "mar 7",
    endDate: "mar 15",
    length: 16,
    cost: 110000,
    quote: false,
    bidID: 54344,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "mar 2",
    endDate: "mar 13",
    length: 11,
    cost: 80000,
    quote: true,
    bidID: 54345,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "mar 6",
    endDate: "mar 18",
    length: 14,
    cost: 120000,
    quote: false,
    bidID: 54346,
  },
];

let job8 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "mar 5",
    endDate: "mar 19",
    length: 13,
    cost: 100000,
    quote: true,
    bidID: 54347,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "mar 9",
    endDate: "mar 17",
    length: 10,
    cost: 85000,
    quote: false,
    bidID: 54348,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "mar",
    endDate: "mar 14",
    length: 12,
    cost: 110000,
    quote: true,
    bidID: 54349,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "mar 4",
    endDate: "mar 16",
    length: 15,
    cost: 95000,
    quote: false,
    bidID: 54350,
  },
];

let job9 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "mar 6",
    endDate: "mar 20",
    length: 14,
    cost: 130000,
    quote: true,
    bidID: 54351,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "mar 2",
    endDate: "mar 14",
    length: 11,
    cost: 90000,
    quote: false,
    bidID: 54352,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "mar 5",
    endDate: "mar 18",
    length: 13,
    cost: 100000,
    quote: true,
    bidID: 54353,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "mar 3",
    endDate: "mar 16",
    length: 16,
    cost: 95000,
    quote: true,
    bidID: 54354,
  },
];

let job10 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "apr 8",
    endDate: "apr 17",
    length: 12,
    cost: 80000,
    quote: false,
    bidID: 54355,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "apr 2",
    endDate: "apr 13",
    length: 10,
    cost: 130000,
    quote: true,
    bidID: 54356,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "apr 7",
    endDate: "apr 16",
    length: 14,
    cost: 110000,
    quote: false,
    bidID: 54357,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "apr 4",
    endDate: "apr 19",
    length: 15,
    cost: 95000,
    quote: true,
    bidID: 54358,
  },
];

let job11 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "apr 3",
    endDate: "apr 15",
    length: 13,
    cost: 105000,
    quote: true,
    bidID: 54359,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "apr 6",
    endDate: "apr 19",
    length: 12,
    cost: 88000,
    quote: false,
    bidID: 54360,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "apr 1",
    endDate: "apr 14",
    length: 9,
    cost: 120000,
    quote: true,
    bidID: 54361,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "apr 5",
    endDate: "apr 18",
    length: 13,
    cost: 100000,
    quote: false,
    bidID: 54362,
  },
];

let job12 = [
  {
    vendor: "amazon",
    uniform2: "abc",
    startDate: "apr 4",
    endDate: "apr 16",
    length: 12,
    cost: 95000,
    quote: true,
    bidID: 54363,
  },
  {
    vendor: "bloomberg",
    uniform2: "abc",
    startDate: "apr 7",
    endDate: "apr 15",
    length: 16,
    cost: 110000,
    quote: false,
    bidID: 54364,
  },
  {
    vendor: "coldgarden",
    uniform2: "abc",
    startDate: "apr 2",
    endDate: "apr 13",
    length: 11,
    cost: 80000,
    quote: true,
    bidID: 54365,
  },
  {
    vendor: "dennys",
    uniform2: "abc",
    startDate: "apr 6",
    endDate: "apr 18",
    length: 14,
    cost: 120000,
    quote: false,
    bidID: 54366,
  },
];

let timeBlock1 = [job1, job2, job3];
let timeBlock2 = [job4, job5, job6];
let timeBlock3 = [job7, job8, job9];
let timeBlock4 = [job10, job11, job12];

export { timeBlock1, timeBlock2, timeBlock3, timeBlock4 };
